---
title: "NYC Taxi Data"
author: "Geoffrey Barry"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(dplyr)
```

```{r}
taxi_data <- X2018_NYC_TAXI_DATA
head(taxi_data)
summary_stats <- summary(taxi_data)
```
```{r}
count = c(250000, 500000, 1000000, 1048575)
ggplot(taxi_data, aes(x = trip_distance)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
  xlim(0, 20) +
  scale_y_continuous(labels = scales::comma)
  labs(title = "Trip Distance Distribution", x = "Distance (miles)", y = "Count")

```

```{r}
pickup_data <- taxi_data %>%
  group_by(pickup_location_id) %>%
  summarize(avg_distance = mean(trip_distance))
```

```{r}
ggplot(pickup_data, aes(x = pickup_location_id, y = avg_distance, color = "red")) +
  geom_line() +
  geom_point() +
  labs(title = "Average Distance by Pickup ID",
       x = "Pickup ID", 
       y = "Average Distance") +
  theme_minimal()
```

```{r}
dropoff_data <- taxi_data %>%
  group_by(dropoff_location_id) %>%
  summarize(avg_distance = mean(trip_distance))
```

```{r}
ggplot(dropoff_data, aes(x = dropoff_location_id, y = avg_distance, color = "red")) +
  geom_line() +
  geom_point() +
  labs(title = "Average Distance by Dropoff ID",
       x = "Dropoff ID", 
       y = "Average Distance") +
  theme_minimal()
```

```{r}
count = c(250000, 500000, 1000000, 1048575)
ggplot(taxi_data, aes(x = pickup_location_id)) +
  geom_bar(binwidth = 1, fill = "yellow", color = "black") +
  xlim(1, 263) +
  scale_y_continuous(labels = scales::comma)
  labs(title = "Pickup Location Distribution", x = "Pickup ID", y = "Count")
```

```{r}
count = c(250000, 500000, 1000000, 1048575)
ggplot(taxi_data, aes(x = dropoff_location_id)) +
  geom_bar(binwidth = 1, fill = "yellow", color = "black") +
  xlim(1, 263) +
  scale_y_continuous(labels = scales::comma)
  labs(title = "Dropoff Location Distribution", x = "Dropoff ID", y = "Count")
```

